import type { ModuleControlSpec } from "./ModuleControlGrid";

export const OSCILLATOR_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "glideMs",
    label: "Glide",
    min: 0,
    max: 120,
    step: 1,
    unit: "ms",
    area: "glideMs",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const DETUNE_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "voices",
    label: "Voices",
    min: 1,
    max: 8,
    step: 1,
    area: "voices",
  },
  {
    type: "knob",
    param: "detune",
    label: "Detune",
    min: 0,
    max: 50,
    step: 0.5,
    unit: "ct",
    area: "detune",
  },
  {
    type: "knob",
    param: "spread",
    label: "Spread",
    min: 0,
    max: 1,
    step: 0.01,
    area: "spread",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
  },
];

export const ENVELOPE_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "attack",
    label: "Atk",
    min: 0.005,
    max: 1,
    step: 0.005,
    unit: "s",
    area: "attack",
  },
  {
    type: "knob",
    param: "decay",
    label: "Dec",
    min: 0.01,
    max: 1,
    step: 0.01,
    unit: "s",
    area: "decay",
  },
  {
    type: "knob",
    param: "sustain",
    label: "Sus",
    min: 0,
    max: 1,
    step: 0.01,
    area: "sustain",
  },
  {
    type: "knob",
    param: "release",
    label: "Rel",
    min: 0.01,
    max: 2,
    step: 0.01,
    unit: "s",
    area: "release",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
  },
  {
    type: "knob",
    param: "cvDepth",
    label: "CV",
    min: 0,
    max: 1200,
    step: 10,
    unit: "Hz",
    area: "cvDepth",
  },
];

export const FORMANT_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "formantShift",
    label: "Morph",
    min: 0,
    max: 1,
    step: 0.01,
    area: "formantShift",
  },
  {
    type: "knob",
    param: "q",
    label: "Q",
    min: 2,
    max: 18,
    step: 0.5,
    area: "q",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const NOISE_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "cutoff",
    label: "Cutoff",
    min: 400,
    max: 12000,
    step: 50,
    unit: "Hz",
    area: "cutoff",
  },
  {
    type: "knob",
    param: "resonance",
    label: "Res",
    min: 0.5,
    max: 12,
    step: 0.1,
    area: "resonance",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const OUTPUT_CONTROLS: ModuleControlSpec[] = [
  {
    type: "fader",
    param: "gain",
    label: "Master",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const LFO_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "rate",
    label: "Rate",
    min: 0.1,
    max: 16,
    step: 0.1,
    unit: "Hz",
    area: "rate",
  },
  {
    type: "knob",
    param: "depth",
    label: "Depth",
    min: 0,
    max: 2000,
    step: 10,
    unit: "Hz",
    area: "depth",
  },
];

export const FM_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "glideMs",
    label: "Glide",
    min: 0,
    max: 120,
    step: 1,
    unit: "ms",
    area: "glideMs",
  },
  {
    type: "knob",
    param: "frequency",
    label: "Freq",
    min: 40,
    max: 400,
    step: 1,
    unit: "Hz",
    area: "frequency",
  },
  {
    type: "knob",
    param: "ratio",
    label: "Ratio",
    min: 0.5,
    max: 8,
    step: 0.1,
    area: "ratio",
  },
  {
    type: "knob",
    param: "index",
    label: "Index",
    min: 0,
    max: 1200,
    step: 10,
    unit: "Hz",
    area: "index",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const DISTORTION_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "drive",
    label: "Drive",
    min: 1,
    max: 12,
    step: 0.1,
    area: "drive",
  },
  {
    type: "knob",
    param: "mix",
    label: "Mix",
    min: 0,
    max: 1,
    step: 0.01,
    area: "mix",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const LAYER_STACK_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "subGain",
    label: "Sub",
    min: 0,
    max: 1,
    step: 0.01,
    area: "subGain",
  },
  {
    type: "knob",
    param: "bodyGain",
    label: "Body",
    min: 0,
    max: 1,
    step: 0.01,
    area: "bodyGain",
  },
  {
    type: "knob",
    param: "topGain",
    label: "Top",
    min: 0,
    max: 1,
    step: 0.01,
    area: "topGain",
  },
  {
    type: "knob",
    param: "subLpf",
    label: "SubLP",
    min: 80,
    max: 250,
    step: 5,
    unit: "Hz",
    area: "subLpf",
  },
  {
    type: "knob",
    param: "bodyHpf",
    label: "BdHP",
    min: 40,
    max: 200,
    step: 5,
    unit: "Hz",
    area: "bodyHpf",
  },
  {
    type: "fader",
    param: "gain",
    label: "Master",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const FILTER_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "cutoff",
    label: "Cutoff",
    min: 80,
    max: 8000,
    step: 10,
    unit: "Hz",
    area: "cutoff",
  },
  {
    type: "knob",
    param: "resonance",
    label: "Res",
    min: 0.1,
    max: 18,
    step: 0.1,
    area: "resonance",
  },
];

export const MIXER_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "gainA",
    label: "Ch A",
    min: 0,
    max: 1,
    step: 0.01,
    area: "gainA",
  },
  {
    type: "knob",
    param: "gainB",
    label: "Ch B",
    min: 0,
    max: 1,
    step: 0.01,
    area: "gainB",
  },
  {
    type: "fader",
    param: "gain",
    label: "Master",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const WAVETABLE_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "glideMs",
    label: "Glide",
    min: 0,
    max: 120,
    step: 1,
    unit: "ms",
    area: "glideMs",
  },
  {
    type: "knob",
    param: "position",
    label: "Morph",
    min: 0,
    max: 1,
    step: 0.01,
    area: "position",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const MULTIBAND_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "amount",
    label: "OTT",
    min: 0,
    max: 1,
    step: 0.01,
    area: "amount",
  },
  {
    type: "knob",
    param: "threshold",
    label: "Thresh",
    min: -48,
    max: 0,
    step: 1,
    unit: "dB",
    area: "threshold",
  },
  {
    type: "knob",
    param: "lowCross",
    label: "LoX",
    min: 80,
    max: 500,
    step: 10,
    unit: "Hz",
    area: "lowCross",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const MOD_FX_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "rate",
    label: "Rate",
    min: 0.05,
    max: 4,
    step: 0.05,
    unit: "Hz",
    area: "rate",
  },
  {
    type: "knob",
    param: "depth",
    label: "Depth",
    min: 0,
    max: 1,
    step: 0.01,
    area: "depth",
  },
  {
    type: "knob",
    param: "mix",
    label: "Mix",
    min: 0,
    max: 1,
    step: 0.01,
    area: "mix",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];

export const FILTER_BANK_CONTROLS: ModuleControlSpec[] = [
  {
    type: "knob",
    param: "f1Cutoff",
    label: "F1",
    min: 80,
    max: 8000,
    step: 10,
    unit: "Hz",
    area: "f1Cutoff",
  },
  {
    type: "knob",
    param: "f2Cutoff",
    label: "F2",
    min: 200,
    max: 12000,
    step: 10,
    unit: "Hz",
    area: "f2Cutoff",
  },
  {
    type: "knob",
    param: "f1Res",
    label: "Q1",
    min: 0.5,
    max: 14,
    step: 0.1,
    area: "f1Res",
  },
  {
    type: "fader",
    param: "gain",
    label: "Level",
    min: 0,
    max: 1,
    step: 0.01,
    area: "fader",
    tall: true,
  },
];
